/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.PersonInfo;
import Model.AddressInfo;
import Model.BankAccountInfo;
import Model.DriverLicenseInfo;
import Model.MedicalRecord;
import Model.ViewReport;

/**
 *
 * @author gowth
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PersonInfo personinfo;
    AddressInfo addressinfo;
    BankAccountInfo savingsaccountinfo;
    DriverLicenseInfo driverlicenseinfo;
    MedicalRecord medicalrecord;
    BankAccountInfo checkingsaccountinfo;
    ViewReport viewreport;
    public MainJFrame() {
        initComponents();
        
        personinfo = new PersonInfo();
        addressinfo = new AddressInfo();
        savingsaccountinfo = new BankAccountInfo();
        driverlicenseinfo = new DriverLicenseInfo();
        medicalrecord = new MedicalRecord();
        checkingsaccountinfo = new BankAccountInfo();
        viewreport = new ViewReport();
        
        setExtendedState(MainJFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitJPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btndemocrt = new javax.swing.JButton();
        btndemoview = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btncreateaddressinfo = new javax.swing.JButton();
        btnviewaddressinfo = new javax.swing.JButton();
        btncreatesavingacctinfo = new javax.swing.JButton();
        btnviewsavingacctinfo = new javax.swing.JButton();
        btncreatedriverlicense = new javax.swing.JButton();
        btnviewdriverlicense = new javax.swing.JButton();
        btncreatemedicalrecord = new javax.swing.JButton();
        btnviewmedicalrecord = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        SplitJPane.setDividerLocation(150);

        btndemocrt.setText("Demographic Info");
        btndemocrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndemocrtActionPerformed(evt);
            }
        });

        btndemoview.setText("Demographic Info");
        btndemoview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndemoviewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Create");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("View");

        btncreateaddressinfo.setText("Address Information");
        btncreateaddressinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateaddressinfoActionPerformed(evt);
            }
        });

        btnviewaddressinfo.setText("Address Information");
        btnviewaddressinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewaddressinfoActionPerformed(evt);
            }
        });

        btncreatesavingacctinfo.setText("Savings Account Info");
        btncreatesavingacctinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatesavingacctinfoActionPerformed(evt);
            }
        });

        btnviewsavingacctinfo.setText("Savings Account Info");
        btnviewsavingacctinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewsavingacctinfoActionPerformed(evt);
            }
        });

        btncreatedriverlicense.setText("Driving License Info");
        btncreatedriverlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatedriverlicenseActionPerformed(evt);
            }
        });

        btnviewdriverlicense.setText("Driving License Info");
        btnviewdriverlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdriverlicenseActionPerformed(evt);
            }
        });

        btncreatemedicalrecord.setText("Medical Record");
        btncreatemedicalrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatemedicalrecordActionPerformed(evt);
            }
        });

        btnviewmedicalrecord.setText("Medical Record");
        btnviewmedicalrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewmedicalrecordActionPerformed(evt);
            }
        });

        jButton1.setText("View Full Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndemocrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndemoview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncreateaddressinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewaddressinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncreatesavingacctinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewsavingacctinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncreatedriverlicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewdriverlicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncreatemedicalrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewmedicalrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndemocrt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncreateaddressinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncreatesavingacctinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncreatedriverlicense)
                .addGap(18, 18, 18)
                .addComponent(btncreatemedicalrecord)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndemoview)
                .addGap(18, 18, 18)
                .addComponent(btnviewaddressinfo)
                .addGap(18, 18, 18)
                .addComponent(btnviewsavingacctinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnviewdriverlicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnviewmedicalrecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitJPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        SplitJPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitJPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitJPane, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndemocrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndemocrtActionPerformed
  CreateJPerson CreatePersonInfo = new CreateJPerson(personinfo,viewreport);
  SplitJPane.setRightComponent(CreatePersonInfo);        // TODO add your handling code here:
    }//GEN-LAST:event_btndemocrtActionPerformed

    private void btndemoviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndemoviewActionPerformed
     ViewJPerson CreatePersonInfo = new ViewJPerson(personinfo);
     SplitJPane.setRightComponent(CreatePersonInfo);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndemoviewActionPerformed

    private void btncreateaddressinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateaddressinfoActionPerformed
       CreateJAddress CreateAddressInfo = new CreateJAddress(addressinfo,viewreport);
  SplitJPane.setRightComponent(CreateAddressInfo);   // TODO add your handling code here:
    }//GEN-LAST:event_btncreateaddressinfoActionPerformed

    private void btnviewaddressinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewaddressinfoActionPerformed
     ViewJAddress ViewPersonInfo = new ViewJAddress(addressinfo);
     SplitJPane.setRightComponent(ViewPersonInfo);
     // TODO add your handling code here:
    }//GEN-LAST:event_btnviewaddressinfoActionPerformed

    private void btncreatesavingacctinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatesavingacctinfoActionPerformed
        CreateJSavingAccount CreateSavingsAcctInfo = new CreateJSavingAccount(savingsaccountinfo,checkingsaccountinfo,viewreport);
  SplitJPane.setRightComponent(CreateSavingsAcctInfo);
// TODO add your handling code here:
    }//GEN-LAST:event_btncreatesavingacctinfoActionPerformed

    private void btnviewsavingacctinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewsavingacctinfoActionPerformed
   ViewJSavingsAccount ViewSavingsAcctInfo = new ViewJSavingsAccount(savingsaccountinfo,checkingsaccountinfo);
  SplitJPane.setRightComponent(ViewSavingsAcctInfo);        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewsavingacctinfoActionPerformed

    private void btncreatedriverlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatedriverlicenseActionPerformed
        CreateJLicenceInfo CreateLicenseInfo = new CreateJLicenceInfo(driverlicenseinfo,viewreport);
        SplitJPane.setRightComponent(CreateLicenseInfo);
// TODO add your handling code here:
    }//GEN-LAST:event_btncreatedriverlicenseActionPerformed

    private void btnviewdriverlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdriverlicenseActionPerformed
    ViewJLicenseInfo ViewLicenseInfo = new ViewJLicenseInfo(driverlicenseinfo);
  SplitJPane.setRightComponent(ViewLicenseInfo);
  // TODO add your handling code here:
    }//GEN-LAST:event_btnviewdriverlicenseActionPerformed

    private void btncreatemedicalrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatemedicalrecordActionPerformed
      CreateJMedical CreateMedical = new CreateJMedical(medicalrecord,viewreport);
        SplitJPane.setRightComponent(CreateMedical);  // TODO add your handling code here:
    }//GEN-LAST:event_btncreatemedicalrecordActionPerformed

    private void btnviewmedicalrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewmedicalrecordActionPerformed
   ViewJMedical ViewMedical = new ViewJMedical(medicalrecord);
        SplitJPane.setRightComponent(ViewMedical);     // TODO add your handling code here:
    }//GEN-LAST:event_btnviewmedicalrecordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ViewJFullReport ViewFullReport = new ViewJFullReport(viewreport);
        SplitJPane.setRightComponent(ViewFullReport);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitJPane;
    private javax.swing.JButton btncreateaddressinfo;
    private javax.swing.JButton btncreatedriverlicense;
    private javax.swing.JButton btncreatemedicalrecord;
    private javax.swing.JButton btncreatesavingacctinfo;
    private javax.swing.JButton btndemocrt;
    private javax.swing.JButton btndemoview;
    private javax.swing.JButton btnviewaddressinfo;
    private javax.swing.JButton btnviewdriverlicense;
    private javax.swing.JButton btnviewmedicalrecord;
    private javax.swing.JButton btnviewsavingacctinfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
