/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Model.BankAccountInfo;
import javax.swing.JOptionPane;
/**
 *
 * @author gowth
 */
public class ViewJSavingsAccount extends javax.swing.JPanel {
BankAccountInfo savingsaccountinfo;
BankAccountInfo checkingsaccountinfo;

    /**
     * Creates new form ViewJSavingsAccount
     */
    public ViewJSavingsAccount(BankAccountInfo savingsaccountinfo,BankAccountInfo checkingsaccountinfo) {
        
        initComponents();
        this.savingsaccountinfo =  savingsaccountinfo;
        this.checkingsaccountinfo = checkingsaccountinfo;
        DisplaySavingsAccountInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsavingbankname = new javax.swing.JTextField();
        txtsavingbankroutingnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsavingbankaccountnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsavingaccountbalance = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcheckingbankroutingnumber = new javax.swing.JTextField();
        txtcheckingbankname = new javax.swing.JTextField();
        txtcheckingbankaccountnumber = new javax.swing.JTextField();
        txtcheckingaccountbalance = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Savings Account Information");

        jLabel2.setText("Bank Name: ");

        jLabel3.setText("Bank Routing Number:");

        txtsavingbankname.setEditable(false);
        txtsavingbankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsavingbanknameActionPerformed(evt);
            }
        });

        txtsavingbankroutingnumber.setEditable(false);
        txtsavingbankroutingnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsavingbankroutingnumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Bank Account Number:");

        txtsavingbankaccountnumber.setEditable(false);
        txtsavingbankaccountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsavingbankaccountnumberActionPerformed(evt);
            }
        });

        jLabel5.setText("Account Balance:");

        txtsavingaccountbalance.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("Checkings Account Information");

        jLabel6.setText("Bank Name: ");

        jLabel7.setText("Bank Routing Number:");

        jLabel9.setText("Bank Account Number:");

        jLabel10.setText("Account Balance:");

        txtcheckingbankroutingnumber.setEditable(false);

        txtcheckingbankname.setEditable(false);

        txtcheckingbankaccountnumber.setEditable(false);

        txtcheckingaccountbalance.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsavingbankname)
                            .addComponent(txtsavingbankroutingnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtsavingbankaccountnumber)
                            .addComponent(txtsavingaccountbalance)
                            .addComponent(txtcheckingbankroutingnumber)
                            .addComponent(txtcheckingbankname)
                            .addComponent(txtcheckingbankaccountnumber)
                            .addComponent(txtcheckingaccountbalance))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsavingbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsavingbankroutingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsavingbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsavingaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcheckingbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcheckingbankroutingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcheckingbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcheckingaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsavingbanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsavingbanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsavingbanknameActionPerformed

    private void txtsavingbankroutingnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsavingbankroutingnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsavingbankroutingnumberActionPerformed

    private void txtsavingbankaccountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsavingbankaccountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsavingbankaccountnumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcheckingaccountbalance;
    private javax.swing.JTextField txtcheckingbankaccountnumber;
    private javax.swing.JTextField txtcheckingbankname;
    private javax.swing.JTextField txtcheckingbankroutingnumber;
    private javax.swing.JTextField txtsavingaccountbalance;
    private javax.swing.JTextField txtsavingbankaccountnumber;
    private javax.swing.JTextField txtsavingbankname;
    private javax.swing.JTextField txtsavingbankroutingnumber;
    // End of variables declaration//GEN-END:variables

    private void DisplaySavingsAccountInfo() {
        txtsavingbankname.setText(savingsaccountinfo.getBankName());
        txtsavingbankroutingnumber.setText(savingsaccountinfo.getBankRoutingNumber());
        txtsavingbankaccountnumber.setText(savingsaccountinfo.getBankAccountNumber());
        txtsavingaccountbalance.setText(savingsaccountinfo.getAccountBalance());  
        
        txtcheckingbankname.setText(checkingsaccountinfo.getBankName());
        txtcheckingbankroutingnumber.setText(checkingsaccountinfo.getBankRoutingNumber());
        txtcheckingbankaccountnumber.setText(checkingsaccountinfo.getBankAccountNumber());
        txtcheckingaccountbalance.setText(checkingsaccountinfo.getAccountBalance()); 
        //To change body of generated methods, choose Tools | Templates.
    }
}
