/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gowth
 */
public class AddCustomerPanel extends javax.swing.JPanel {

    
    public CustomerDirectory customerDirectory;
    public JPanel container;
    public EcoSystem system;

    /**
     * Creates new form AddCustomerPanel
     */
    
    
    public AddCustomerPanel(JPanel container, EcoSystem system, CustomerDirectory customerDirectory) {
        initComponents();
        this.customerDirectory = customerDirectory;
        this.container = container;
        this.system = system;
        System.out.println(system);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcustomername = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtemailid = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtlandmark = new javax.swing.JTextField();
        txtzipcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btncreatecustomer = new javax.swing.JButton();
        btnbackaction = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Add Customer");

        jLabel2.setText("Customer Name:");

        jLabel3.setText("Password:");

        jLabel4.setText("Email ID:");

        jLabel5.setText("Username:");

        jLabel6.setText("Phone Number:");

        jLabel7.setText("Address:");

        jLabel8.setText("LandMark:");

        jLabel9.setText("Zipcode:");

        btncreatecustomer.setText("Submit Customer");
        btncreatecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatecustomerActionPerformed(evt);
            }
        });

        btnbackaction.setText("Back");
        btnbackaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbackaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcustomername, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtusername)
                            .addComponent(txtpassword)
                            .addComponent(txtemailid))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncreatecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtphonenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtaddress)
                    .addComponent(txtzipcode)
                    .addComponent(txtlandmark))
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreatecustomer)
                    .addComponent(btnbackaction))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackactionActionPerformed
         container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UpdateCustomerJPanel manageCustomersJPanel = (UpdateCustomerJPanel) component;
        manageCustomersJPanel.populateCustomerList();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnbackactionActionPerformed

    private void btncreatecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatecustomerActionPerformed
        // TODO add your handling code here:
        String name = txtcustomername.getText();
        String phone = txtphonenumber.getText();
        String streetAddress = txtaddress.getText();
        String zipCode = txtzipcode.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String email = txtemailid.getText();
        String landmark = txtlandmark.getText();
        

        if (name.isEmpty() || phone.isEmpty() || streetAddress.isEmpty() || zipCode.isEmpty() || username.isEmpty() || password.isEmpty() || email.isEmpty() || landmark.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
        } else if (!system.checkValidPhoneFormat(phone)) {
            JOptionPane.showMessageDialog(null, "Please Enter Correct Phone Format.");
        } else if (!system.checkValidEmailFormat(email)) {
            JOptionPane.showMessageDialog(null, "Email format incorrect!");
        } else if (!customerDirectory.isEmailUnique(email)) {
            JOptionPane.showMessageDialog(null, "Sorry! User with this email already exist!");
        } else if (!customerDirectory.isPhoneUnique(phone)) {
            JOptionPane.showMessageDialog(null, "Sorry! User with this phone no already exist!");
        } else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(null, "Sorry! User with this username already exist!");
        } else {
            Customer customer = new Customer();
            customer.setCustomerID(customerDirectory.generateCustomerID());
            customer.setCustomerName(name);
            customer.setCustomerPhonenumber(phone);
            customer.setCustomerAddress(streetAddress);
            customer.setCustomerZipcode(zipCode);
            customer.setCustomerEmail(email);
            customer.setLandMark(landmark);
           // customer.setLandMark();
            customerDirectory.add(customer);
            Employee employee = system.getEmployeeDirectory().createEmployee(customer.getCustomerID());
            system.setCustomerDirectory(customerDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(username, password, employee, new CustomerRole());
            JOptionPane.showMessageDialog(null, "Customer is added to the system!");
            emptyAllFields();
        }
    }//GEN-LAST:event_btncreatecustomerActionPerformed

//private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//        String name = txtcustomername.getText();
//        String phone = txtphonenumber.getText();
//        String streetAddress = txtaddress.getText();
//        String zipCode = txtzipcode.getText();
//        String username = txtusername.getText();
//        String password = txtpassword.getText();
//        String email = txtemailid.getText();
//        String landmark = txtlandmark.getText();
//        
//
//        if (name.isEmpty() || phone.isEmpty() || streetAddress.isEmpty() || zipCode.isEmpty() || username.isEmpty() || password.isEmpty() || email.isEmpty() || landmark.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Please enter all fields!");
//        } else if (!system.checkValidPhoneFormat(phone)) {
//            JOptionPane.showMessageDialog(null, "Please Enter Correct Phone Format.");
//        } else if (!system.checkValidEmailFormat(email)) {
//            JOptionPane.showMessageDialog(null, "Email format incorrect!");
//        } else if (!customerDirectory.isEmailUnique(email)) {
//            JOptionPane.showMessageDialog(null, "Sorry! User with this email already exist!");
//        } else if (!customerDirectory.isPhoneUnique(phone)) {
//            JOptionPane.showMessageDialog(null, "Sorry! User with this phone no already exist!");
//        } else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
//            JOptionPane.showMessageDialog(null, "Sorry! User with this username already exist!");
//        } else {
//            Customer customer = new Customer();
//            customer.setCustomerID(customerDirectory.generateCustomerID());
//            customer.setCustomerName(name);
//            customer.setCustomerPhonenumber(phone);
//            customer.setCustomerAddress(streetAddress);
//            customer.setCustomerZipcode(zipCode);
//            customer.setCustomerEmail(email);
//            customer.setLandMark(landmark);
//           // customer.setLandMark();
//            customerDirectory.add(customer);
//            Employee employee = system.getEmployeeDirectory().createEmployee(customer.getCustomerID());
//            system.setCustomerDirectory(customerDirectory);
//            UserAccount account = system.getUserAccountDirectory().createUserAccount(username, password, employee, new CustomerRole());
//            JOptionPane.showMessageDialog(null, "Customer is added to the system!");
//            emptyAllFields();
//        }
//    }                                         
    public void emptyAllFields() {
        txtcustomername.setText("");
        txtphonenumber.setText("");
        txtaddress.setText("");
        txtzipcode.setText("");
        txtpassword.setText("");
        txtusername.setText("");
        txtemailid.setText("");
        txtlandmark.setText("");
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TO dO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UpdateCustomerJPanel manageCustomersJPanel = (UpdateCustomerJPanel) component;
        manageCustomersJPanel.populateCustomerList();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }                                       

    private void txtZipcodeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbackaction;
    private javax.swing.JButton btncreatecustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtlandmark;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtusername;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables
}
