/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gowth
 */
public class ManageRestaurantPanel extends javax.swing.JPanel {

    public RestaurantDirectory restaurantDirectory;
    public JPanel container;
    public EcoSystem system;

    /**
     * Creates new form ManageRestaurantPanel
     */
    public ManageRestaurantPanel(JPanel container, EcoSystem system, RestaurantDirectory restaurantDirectory) {
        initComponents();
        
        this.container = container;
        this.restaurantDirectory = restaurantDirectory;
        this.system = system;

        populateRestaurants();
    }

    
     public void populateRestaurants() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    DefaultTableModel model = (DefaultTableModel) tblrestaurantview.getModel();

        model.setRowCount(0);
        for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
            for (Restaurant restaurant : restaurantDirectory.getRestaurantDirectory()) {
                if (restaurant.getRestaurantID().equalsIgnoreCase(ua.getEmployee().getName())) {
                    Object[] row = new Object[6];
                    row[0] = restaurant.getRestaurantID();
                    row[1] = restaurant.getRestaurantName();
                    row[2] = restaurant.getStreetAddress();
                    row[3] = restaurant.getMobileNo();
                    row[4] = restaurant.getZipcode();                    
                    row[5] = restaurant.getEmail();
                    model.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrestaurantview = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        btnaddrestaurant = new javax.swing.JButton();
        btnupdaterestaurant = new javax.swing.JButton();
        btndeleterestaurant = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Manage Restaurants");

        tblrestaurantview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Restaurant ID", "Restaurant Name", "Address", "Phone Number", "Zipcode", "Email ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblrestaurantview);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnaddrestaurant.setText("Add Restaurant");
        btnaddrestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddrestaurantActionPerformed(evt);
            }
        });

        btnupdaterestaurant.setText("Update Restaurant");
        btnupdaterestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdaterestaurantActionPerformed(evt);
            }
        });

        btndeleterestaurant.setText("Delete Restaurant");
        btndeleterestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleterestaurantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnback)
                                .addGap(85, 85, 85)
                                .addComponent(btnaddrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnupdaterestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(btndeleterestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnaddrestaurant)
                    .addComponent(btnupdaterestaurant)
                    .addComponent(btndeleterestaurant))
                .addGap(146, 146, 146))
        );
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnaddrestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddrestaurantActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        AddRestaurantPanel createRestaurantJPanel = new AddRestaurantPanel(container, system, restaurantDirectory);
        container.add(createRestaurantJPanel);
        layout.next(container);
    }//GEN-LAST:event_btnaddrestaurantActionPerformed

    private void btnupdaterestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdaterestaurantActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblrestaurantview.getSelectedRow();
        int count = tblrestaurantview.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                CardLayout layout = (CardLayout) container.getLayout();
                Restaurant restaurant = restaurantDirectory.getRestaurantNo(selectedRow);
                UpdateRestaurantPanel UpdateRestaurantsJPanel = new UpdateRestaurantPanel(container, restaurant);
                container.add(UpdateRestaurantsJPanel);
                layout.next(container);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Restaurant to update");
        }
    }//GEN-LAST:event_btnupdaterestaurantActionPerformed

    private void btndeleterestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleterestaurantActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblrestaurantview.getSelectedRow();
        int count = tblrestaurantview.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
                if (selectionResult == JOptionPane.YES_OPTION) {
                    restaurantDirectory.deleteRestaurant(selectedRow, system);
                    populateRestaurants();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btndeleterestaurantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddrestaurant;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndeleterestaurant;
    private javax.swing.JButton btnupdaterestaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblrestaurantview;
    // End of variables declaration//GEN-END:variables

    
}
